    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- ADD THIS STEP BELOW ---
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      # ---------------------------

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # Change 'npm' to 'pnpm' here

      - name: Install dependencies
        run: pnpm install # Change 'npm install' to 'pnpm install'
        
      - name: Build APK
        run: pnpm run build # Change 'npm run build' to 'pnpm run build'
